# Generated by Django 6.0.2 on 2026-02-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_trip_status_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="current_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("off_duty", "Off Duty"),
                    ("sleeper", "Sleeper Berth"),
                    ("driving", "Driving"),
                    ("on_duty", "On Duty (Not Driving)"),
                ],
                default="off_duty",
                max_length=20,
                null=True,
            ),
        ),
    ]
