# Generated by Django 6.0.2 on 2026-02-19 22:12

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_trip"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="current_location",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trip",
            name="pickup_location",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trip",
            name="dropoff_location",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trip",
            name="current_status_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="route_distance_miles",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="route_duration_hours",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="route_polyline",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="route_stops",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="cycle_used_hours",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name="trip",
            name="current_status",
            field=models.CharField(
                choices=[
                    ("off_duty", "Off Duty"),
                    ("sleeper", "Sleeper Berth"),
                    ("driving", "Driving"),
                    ("on_duty", "On Duty (Not Driving)"),
                ],
                default="off_duty",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="StatusEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("off_duty", "Off Duty"), ("sleeper", "Sleeper Berth"), ("driving", "Driving"), ("on_duty", "On Duty (Not Driving)")], max_length=20)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("trip", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="status_events", to="api.trip")),
            ],
        ),
    ]
