"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
import os
import shutil
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ENV_FILE = BASE_DIR / ".env"


def load_env_file(path: Path) -> None:
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if not key:
            continue
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]
        os.environ.setdefault(key, value)


load_env_file(ENV_FILE)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def parse_bool(value: str, default: bool) -> bool:
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def parse_csv(value: str, default: list[str]) -> list[str]:
    if not value:
        return default
    return [item.strip() for item in value.split(",") if item.strip()]


def parse_int(value: str, default: int) -> int:
    if value is None:
        return default
    try:
        return int(value.strip())
    except (TypeError, ValueError):
        return default


IS_VERCEL = parse_bool(os.getenv("VERCEL"), False)


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-ql91!j8!*(_os%46vb2emivmj6u25h^11v8m6^k3z!b((wd7jf",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = parse_bool(os.getenv("DJANGO_DEBUG"), not IS_VERCEL)

ALLOWED_HOSTS = parse_csv(
    os.getenv("DJANGO_ALLOWED_HOSTS"),
    ["127.0.0.1", "localhost", ".vercel.app"],
)


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'api.middleware.ApiAuthMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.app'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

default_sqlite_path = BASE_DIR / "db.sqlite3"
if IS_VERCEL:
    # Vercel filesystem is read-only except /tmp, so copy the seeded DB once per cold start.
    vercel_sqlite_path = Path("/tmp/db.sqlite3")
    if not vercel_sqlite_path.exists() and default_sqlite_path.exists():
        try:
            shutil.copy2(default_sqlite_path, vercel_sqlite_path)
        except OSError:
            pass
    sqlite_db_path = vercel_sqlite_path
else:
    sqlite_db_path = default_sqlite_path

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': sqlite_db_path,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Enable WhiteNoise compression and caching for static files
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = parse_bool(os.getenv("DJANGO_SECURE_SSL_REDIRECT"), IS_VERCEL)
SESSION_COOKIE_SECURE = parse_bool(os.getenv("DJANGO_SESSION_COOKIE_SECURE"), IS_VERCEL)
CSRF_COOKIE_SECURE = parse_bool(os.getenv("DJANGO_CSRF_COOKIE_SECURE"), IS_VERCEL)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'api.User'

CORS_ALLOWED_ORIGINS = parse_csv(
    os.getenv("DJANGO_CORS_ALLOWED_ORIGINS"),
    ["http://localhost:5173", "http://127.0.0.1:5173"],
)
CORS_ALLOW_CREDENTIALS = parse_bool(os.getenv("DJANGO_CORS_ALLOW_CREDENTIALS"), True)
CSRF_TRUSTED_ORIGINS = parse_csv(
    os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS"),
    ["http://localhost:5173", "http://127.0.0.1:5173", "https://*.vercel.app"],
)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.authentication.CookieJWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}

JWT_AUTH_COOKIE = 'access_token'
JWT_AUTH_REFRESH_COOKIE = 'refresh_token'
JWT_COOKIE_SECURE = parse_bool(os.getenv("DJANGO_JWT_COOKIE_SECURE"), IS_VERCEL)
JWT_COOKIE_SAMESITE = os.getenv("DJANGO_JWT_COOKIE_SAMESITE", "Lax")
GEOCODING_USER_AGENT = os.getenv(
    "GEOCODING_USER_AGENT",
    "spotter-eld/1.0 (development)",
)
POI_USER_AGENT = os.getenv(
    "POI_USER_AGENT",
    "spotter-eld/1.0 (development)",
)
ROUTING_USER_AGENT = os.getenv(
    "ROUTING_USER_AGENT",
    "spotter-eld/1.0 (development)",
)
POI_BASE_URL = os.getenv("POI_BASE_URL", "https://overpass-api.de/api/interpreter")
POI_DEFAULT_RADIUS_KM = max(1, parse_int(os.getenv("POI_DEFAULT_RADIUS_KM"), 15))
POI_DEFAULT_LIMIT_PER_CATEGORY = max(1, parse_int(os.getenv("POI_DEFAULT_LIMIT_PER_CATEGORY"), 3))
ORS_API_KEY = os.getenv("ORS_API_KEY", "")
ORS_DIRECTIONS_PROFILE = os.getenv("ORS_DIRECTIONS_PROFILE", "driving-hgv")
ORS_BASE_URL = os.getenv("ORS_BASE_URL", "https://api.openrouteservice.org").rstrip("/")
ORS_DIRECTIONS_URL = f"{ORS_BASE_URL}/v2/directions/{ORS_DIRECTIONS_PROFILE}/geojson"
ORS_SNAP_RADIUS_METERS = max(350, parse_int(os.getenv("ORS_SNAP_RADIUS_METERS"), 5000))
