from django.urls import path
from .views import (
    ActiveTripView,
    CompletedEldLogsView,
    EldLogsView,
    GeocodeReverseView,
    GeocodeSearchView,
    LoginView,
    NearbyPoiView,
    LogoutView,
    RefreshView,
    MeView,
    StatusEventCreateView,
    TripCompleteView,
    TripCreateView,
    TripRoutePreviewView,
    TripRouteView,
    TripSummaryView,
    TestView,
)

urlpatterns=[
   path("auth/login/", LoginView.as_view(), name="login"),
   path("auth/logout/", LogoutView.as_view(), name="logout"),
   path("auth/refresh/", RefreshView.as_view(), name="refresh"),
   path("auth/me/", MeView.as_view(), name="me"),
   path("geocode/search/", GeocodeSearchView.as_view(), name="geocode-search"),
   path("geocode/reverse/", GeocodeReverseView.as_view(), name="geocode-reverse"),
   path("pois/nearby/", NearbyPoiView.as_view(), name="nearby-pois"),
   path("trips/active/", ActiveTripView.as_view(), name="trip-active"),
   path("trips/preview-route/", TripRoutePreviewView.as_view(), name="trip-route-preview"),
   path("trips/", TripCreateView.as_view(), name="trip-create"),
   path("trips/<uuid:trip_id>/", TripSummaryView.as_view(), name="trip-summary"),
   path("trips/<uuid:trip_id>/route/", TripRouteView.as_view(), name="trip-route"),
   path("trips/<uuid:trip_id>/status-events/", StatusEventCreateView.as_view(), name="trip-status-event"),
   path("trips/<uuid:trip_id>/complete/", TripCompleteView.as_view(), name="trip-complete"),
   path("trips/<uuid:trip_id>/eld-logs/", EldLogsView.as_view(), name="trip-eld-logs"),
   path("trips/completed/eld-logs/", CompletedEldLogsView.as_view(), name="trip-completed-eld-logs"),
   path("test/", TestView.as_view(), name="test-endpoint"),
]
